---
  - name: "ECS service task def"
      ecs_taskdefinition:
        region: us-east-1
        containers:
          - name: "{{ container_name }}"
            cpu: "{{ container_cpu }}"
            essential: true
            image: "{{ ecr_image_repo}}"
            memory: "{{ container_memory }}"
            portMappings:
              - containerPort: "{{ container_port }}"
                hostPort: "{{ host_port }}"
            environment:
              - name: ENV
                value: "{{ container_env}}"
        family: "{{ my_ecs_task_definition_family }}"
        state: present
      register: ecs_taskdefinition_output


  - name: "ECS | Provision a service using task def"
      ecs_service:
        region: us-east-1
        state: present
        name: "{{ my_ecs_service_name }}"
        cluster: "{{ my_ecs_cluster_name }}"
        task_definition: "{{ my_ecs_task_definition_family }}:{{ output.stdout }}"
        desired_count: "{{ my_ecs_task_definition_count }}" 
        role: "{{ my_ecs_iam_role }}"
        load_balancers:
          - targetGroupArn: "{{container_targetarn}}"
            containerName: "{{ container_name }}"
            containerPort: "{{ container_port }}"
